services:
  db:
    container_name: todo-db
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  app:
    container_name: todo-app
    build:
      context: .
      target: dev-build
    restart: always
    depends_on:
      - db
    tty: true
    stdin_open: true

    volumes:
      - .:/app

networks:
  default:
    name: todo-network
